---
dist: xenial
# Config file for automatic testing at travis-ci.org
services:
  - docker
language: python

jobs:
  fast_finish: true
  include:
    # combined env improve execution speed on travis considerably
    - name: lint,py27,distros
      python: "3.7"
      env: TOXENV=lint,py27,distros
    - name: py35
      python: "3.5"
      env: TOXENV=py35
    - name: py36
      python: "3.6"
      env: TOXENV=py36
    - name: py37
      python: "3.7"
      env: TOXENV=py37
    - name: devel
      python: "3.7"
      env: TOXENV=devel
    - stage: deploy
      name: deploy
      if: tag IS present AND type != cron
      env: TOXENV=upload

install:
  - pip install tox

script:
  - travis_wait tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - lxc
      - lxc-dev
      - lxd
      - lxd-client
